In [85]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score,precision_score,f1_score
from sklearn.preprocessing import LabelEncoder

In [87]:
df=pd.read_csv("heart.csv")
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [89]:
x=df.drop('target',axis=1)

In [91]:
y=df['target']

In [93]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=25)

# LogesticRegression model Accuracy_score

In [96]:
lr=LogisticRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.8131868131868132
[[28 12]
 [ 5 46]]

/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

# decisionTree Model Accuracy_score

In [99]:
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)
y_pred1=dt.predict(x_test)
print(accuracy_score(y_test,y_pred1))
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))

0.7582417582417582

    0   1
0  30  10
1  12  39

In [101]:
result=pd.DataFrame()
result['actual Label']= y_test
result['LogisticRegression']=y_pred
result['DecisionTree']=y_pred1
result.sample(10)

     actual Label  LogisticRegression  DecisionTree
133             1                   1             1
18              1                   1             1
218             0                   0             0
250             0                   0             0
196             0                   1             1
111             1                   1             0
19              1                   1             1
200             0                   1             0
117             1                   1             1
73              1                   1             1

In [103]:
print("For Logistic regression Model")
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred),columns=list(range(0,2)))
print(cdf)
print("Precision - ",precision_score(y_test,y_pred))
print("Recall - ",recall_score(y_test,y_pred))
print("F1 score - ",f1_score(y_test,y_pred))

For Logistic regression Model
    0   1
0  28  12
1   5  46
Precision -  0.7931034482758621
Recall -  0.9019607843137255
F1 score -  0.8440366972477065

In [105]:
print("For Decision tree  Model")
ddf = pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))
print(ddf)
print("Precision - ",precision_score(y_test,y_pred1))
print("Recall - ",recall_score(y_test,y_pred1))
print("F1 score - ",f1_score(y_test,y_pred1))

For Decision tree  Model
    0   1
0  30  10
1  12  39
Precision -  0.7959183673469388
Recall -  0.7647058823529411
F1 score -  0.78

In [113]:
precision_score(y_test,y_pred,average=None)

array([0.84848485, 0.79310345])

In [115]:
precision_score(y_test,y_pred1,average=None)

array([0.71428571, 0.79591837])